name: Release
on:
  push:
    tags:
      - v.*

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - id: prep
        run: |
          OWNER_LC=${GITHUB_REPOSITORY,,}
          echo ::set-output name=tags::ghcr.io/${OWNER_LC}:${GITHUB_REF#refs/tags/v}

      - name: Checkout code
        uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v1

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ steps.prep.outputs.tags }}
          push: true
          platforms: linux/amd64,linux/arm64,linux/386
